services:
  - type: web
    name: hackathon-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        value: hackathon_db
      - key: CORS_ORIGIN
        value: https://your-frontend-domain.com 