// Frontend/src/components/ui/Icon.jsx
import React from 'react';
import * as LucideIcons from 'lucide-react';

const Icon = ({ 
  name, 
  size = 20, 
  className = "", 
  color = "currentColor",
  ...props 
}) => {
  const IconComponent = LucideIcons[name];
  
  if (!IconComponent) {
    console.warn(`Icon "${name}" not found`);
    return null;
  }
  
  return (
    <IconComponent 
      size={size} 
      className={`text-current ${className}`}
      style={{ color }}
      {...props}
    />
  );
};

// Icon mapping for common emoji replacements
export const iconMap = {
  // Navigation & Actions
  '🏠': 'Home',
  '👤': 'User',
  '⚙️': 'Settings',
  '📊': 'BarChart3',
  '🏆': 'Trophy',
  '👥': 'Users',
  '➕': 'Plus',
  '✏️': 'Edit',
  '🗑️': 'Trash2',
  '✅': 'Check',
  '❌': 'X',
  '🔍': 'Search',
  '📝': 'FileText',
  '📤': 'Upload',
  '📥': 'Download',
  
  // Status & Feedback
  '🎉': 'PartyPopper',
  '⚠️': 'AlertTriangle',
  '❓': 'HelpCircle',
  '💡': 'Lightbulb',
  '🔒': 'Lock',
  '🔓': 'Unlock',
  '📧': 'Mail',
  '📱': 'Smartphone',
  '🌐': 'Globe',
  '💬': 'MessageSquare',
  '📅': 'Calendar',
  '⏰': 'Clock',
  '🎯': 'Target',
  '🔗': 'Link',
  '📋': 'Clipboard',
  '🎨': 'Palette',
  '🚀': 'Rocket',
  '⭐': 'Star',
  '💎': 'Gem',
  '🔥': 'Flame',
  '💪': 'Zap',
  '🎪': 'Zap',
  '🌟': 'Sparkles',
  
  // Team & Collaboration
  '🤝': 'Handshake',
  '👨‍💻': 'User',
  '👩‍💻': 'User',
  '👨‍🎓': 'GraduationCap',
  '👩‍🎓': 'GraduationCap',
  '👨‍🏫': 'User',
  '👩‍🏫': 'User',
  
  // Technology
  '💻': 'Laptop',
  '🖥️': 'Monitor',
  '⌨️': 'Keyboard',
  '🖱️': 'Mouse',
  '📱': 'Smartphone',
  '📟': 'Smartphone',
  '📺': 'Monitor',
  '📻': 'Radio',
  '🎧': 'Headphones',
  '🎤': 'Mic',
  '📷': 'Camera',
  '📹': 'Video',
  '🎬': 'Video',
  '🎥': 'Video',
  
  // Communication
  '📞': 'Phone',
  '📠': 'Fax',
  '📨': 'Mail',
  '📩': 'Mail',
  '📪': 'Mailbox',
  '📫': 'Mailbox',
  '📬': 'Mailbox',
  '📭': 'Mailbox',
  '📮': 'Mailbox',
  '🗳️': 'Vote',
  '✉️': 'Mail',
  '📤': 'Send',
  '📥': 'Inbox',
  
  // Files & Documents
  '📄': 'FileText',
  '📃': 'FileText',
  '📑': 'BookOpen',
  '📊': 'BarChart3',
  '📈': 'TrendingUp',
  '📉': 'TrendingDown',
  '📋': 'Clipboard',
  '📌': 'Pin',
  '📍': 'MapPin',
  '📎': 'Paperclip',
  '🖇️': 'Link',
  '📏': 'Ruler',
  '📐': 'Ruler',
  '✂️': 'Scissors',
  '🗂️': 'Folder',
  '🗃️': 'Archive',
  '🗄️': 'Archive',
  '🗑️': 'Trash2',
  
  // Time & Calendar
  '⏰': 'Clock',
  '🕐': 'Clock',
  '🕑': 'Clock',
  '🕒': 'Clock',
  '🕓': 'Clock',
  '🕔': 'Clock',
  '🕕': 'Clock',
  '🕖': 'Clock',
  '🕗': 'Clock',
  '🕘': 'Clock',
  '🕙': 'Clock',
  '🕚': 'Clock',
  '🕛': 'Clock',
  '⏱️': 'Timer',
  '⏲️': 'Timer',
  '⏳': 'Hourglass',
  '⌛': 'Hourglass',
  '📅': 'Calendar',
  '📆': 'Calendar',
  '🗓️': 'Calendar',
  
  // Security & Privacy
  '🔐': 'Lock',
  '🔑': 'Key',
  '🗝️': 'Key',
  '🔒': 'Lock',
  '🔓': 'Unlock',
  '🛡️': 'Shield',
  '🛠️': 'Wrench',
  '⚒️': 'Hammer',
  '🔨': 'Hammer',
  '🔧': 'Wrench',
  '🔩': 'Nut',
  '⚙️': 'Settings',
  '⚖️': 'Scale',
  '🔗': 'Link',
  '⛓️': 'Link',
  
  // Success & Status
  '✅': 'Check',
  '✔️': 'Check',
  '☑️': 'Check',
  '❌': 'X',
  '❎': 'X',
  '➕': 'Plus',
  '➖': 'Minus',
  '✖️': 'X',
  '➗': 'Divide',
  '🔄': 'RefreshCw',
  '🔁': 'Repeat',
  '🔂': 'Repeat',
  '⏭️': 'SkipForward',
  '⏮️': 'SkipBack',
  '⏯️': 'Play',
  '⏹️': 'Square',
  '⏺️': 'Record',
  '⏏️': 'Eject',
  
  // Arrows & Navigation
  '⬆️': 'ArrowUp',
  '⬇️': 'ArrowDown',
  '⬅️': 'ArrowLeft',
  '➡️': 'ArrowRight',
  '↗️': 'ArrowUpRight',
  '↘️': 'ArrowDownRight',
  '↙️': 'ArrowDownLeft',
  '↖️': 'ArrowUpLeft',
  '↕️': 'ArrowUpDown',
  '↔️': 'ArrowLeftRight',
  '🔄': 'RefreshCw',
  '🔃': 'RotateCcw',
  '🔙': 'ArrowLeft',
  '🔚': 'ArrowRight',
  '🔛': 'ToggleLeft',
  '🔜': 'ArrowRight',
  '🔝': 'ArrowUp',
  
  // Weather & Environment
  '☀️': 'Sun',
  '🌤️': 'CloudSun',
  '⛅': 'Cloud',
  '🌦️': 'CloudRain',
  '🌧️': 'CloudRain',
  '⛈️': 'CloudLightning',
  '🌩️': 'Zap',
  '🌨️': 'CloudSnow',
  '❄️': 'Snowflake',
  '☔': 'Umbrella',
  '⛱️': 'Umbrella',
  '🌈': 'Rainbow',
  '🌊': 'Waves',
  '🌋': 'Mountain',
  '🗻': 'Mountain',
  '🏔️': 'Mountain',
  '⛰️': 'Mountain',
  '🌲': 'TreePine',
  '🌳': 'TreePine',
  '🌴': 'PalmTree',
  '🌵': 'Cactus',
  '🌶️': 'Pepper',
  '🌷': 'Flower',
  '🌸': 'CherryBlossom',
  '🌹': 'Rose',
  '🌺': 'Flower',
  '🌻': 'Sunflower',
  '🌼': 'Flower',
  '🌽': 'Corn',
  '🌾': 'Wheat',
  '🌿': 'Leaf',
  '🍀': 'Clover',
  '🍁': 'Leaf',
  '🍂': 'Leaf',
  '🍃': 'Leaf',
  
  // Food & Drinks
  '🍎': 'Apple',
  '🍊': 'Orange',
  '🍋': 'Lemon',
  '🍌': 'Banana',
  '🍉': 'Watermelon',
  '🍇': 'Grapes',
  '🍓': 'Strawberry',
  '🍈': 'Melon',
  '🍒': 'Cherry',
  '🍑': 'Peach',
  '🥭': 'Mango',
  '🍍': 'Pineapple',
  '🥥': 'Coconut',
  '🥝': 'Kiwi',
  '🍅': 'Tomato',
  '🍆': 'Eggplant',
  '🥑': 'Avocado',
  '🥦': 'Broccoli',
  '🥬': 'Lettuce',
  '🥒': 'Cucumber',
  '🌶️': 'Pepper',
  '🌽': 'Corn',
  '🥕': 'Carrot',
  '🥔': 'Potato',
  '🍠': 'SweetPotato',
  '🥐': 'Croissant',
  '🥖': 'Baguette',
  '🍞': 'Bread',
  '🥨': 'Pretzel',
  '🥯': 'Bagel',
  '🥞': 'Pancakes',
  '🧀': 'Cheese',
  '🍖': 'Meat',
  '🍗': 'Chicken',
  '🥩': 'Steak',
  '🥓': 'Bacon',
  '🍔': 'Hamburger',
  '🍟': 'Fries',
  '🍕': 'Pizza',
  '🌭': 'Hotdog',
  '🥪': 'Sandwich',
  '🌮': 'Taco',
  '🌯': 'Burrito',
  '🥙': 'Kebab',
  '🥚': 'Egg',
  '🍳': 'FriedEgg',
  '🥘': 'Paella',
  '🍲': 'Stew',
  '🥗': 'Salad',
  '🍿': 'Popcorn',
  '🧈': 'Butter',
  '🧂': 'Salt',
  '🥫': 'CannedFood',
  '🍱': 'Bento',
  '🍘': 'RiceCracker',
  '🍙': 'RiceBall',
  '🍚': 'Rice',
  '🍛': 'Curry',
  '🍜': 'Ramen',
  '🍝': 'Spaghetti',
  '🍠': 'SweetPotato',
  '🍢': 'Oden',
  '🍣': 'Sushi',
  '🍤': 'Shrimp',
  '🍥': 'FishCake',
  '🥮': 'MoonCake',
  '🍡': 'Dango',
  '🥟': 'Dumpling',
  '🥠': 'FortuneCookie',
  '🥡': 'TakeoutBox',
  
  // Drinks
  '🍶': 'Sake',
  '🍷': 'Wine',
  '🍸': 'Cocktail',
  '🍹': 'TropicalDrink',
  '🍺': 'Beer',
  '🍻': 'Beers',
  '🥂': 'Champagne',
  '🥃': 'Whiskey',
  '🥤': 'SoftDrink',
  '🧃': 'Juice',
  '🧉': 'Mate',
  '🧊': 'Ice',
  
  // Sports & Activities
  '⚽': 'Soccer',
  '🏀': 'Basketball',
  '🏈': 'Football',
  '⚾': 'Baseball',
  '🥎': 'Softball',
  '🎾': 'Tennis',
  '🏐': 'Volleyball',
  '🏉': 'Rugby',
  '🎱': 'Pool',
  '🏓': 'PingPong',
  '🏸': 'Badminton',
  '🏒': 'Hockey',
  '🏑': 'FieldHockey',
  '🥍': 'Lacrosse',
  '🏏': 'Cricket',
  '🪃': 'Boomerang',
  '🎣': 'Fishing',
  '🤿': 'Diving',
  '🎽': 'Running',
  '🎿': 'Skiing',
  '🛷': 'Sled',
  '🥌': 'Curling',
  '🎯': 'Target',
  '🪁': 'Kite',
  '🎪': 'Circus',
  '🤹': 'Juggling',
  '🎭': 'Theater',
  '🩰': 'Ballet',
  '🎨': 'Palette',
  '🎬': 'Video',
  '🎤': 'Mic',
  '🎧': 'Headphones',
  '🎼': 'Music',
  '🎵': 'Music',
  '🎶': 'Music',
  '🪘': 'Drum',
  '🥁': 'Drum',
  '🎹': 'Piano',
  '🎷': 'Saxophone',
  '🎺': 'Trumpet',
  '🎻': 'Violin',
  '🪗': 'Accordion',
  '🎸': 'Guitar',
  '🎻': 'Violin',
  '🪕': 'Banjo',
  '🎺': 'Trumpet',
  '🎷': 'Saxophone',
  '🎹': 'Piano',
  '🥁': 'Drum',
  '🪘': 'Drum',
  '🎶': 'Music',
  '🎵': 'Music',
  '🎼': 'Music',
  '🎧': 'Headphones',
  '🎤': 'Mic',
  '🎬': 'Video',
  '🎨': 'Palette',
  '🩰': 'Ballet',
  '🎭': 'Theater',
  '🤹': 'Juggling',
  '🎪': 'Circus',
  '🪁': 'Kite',
  '🎯': 'Target',
  '🥌': 'Curling',
  '🛷': 'Sled',
  '🎿': 'Skiing',
  '🎽': 'Running',
  '🤿': 'Diving',
  '🎣': 'Fishing',
  '🪃': 'Boomerang',
  '🏏': 'Cricket',
  '🥍': 'Lacrosse',
  '🏑': 'FieldHockey',
  '🏒': 'Hockey',
  '🏸': 'Badminton',
  '🏓': 'PingPong',
  '🎱': 'Pool',
  '🏉': 'Rugby',
  '🏐': 'Volleyball',
  '🎾': 'Tennis',
  '🥎': 'Softball',
  '⚾': 'Baseball',
  '🏈': 'Football',
  '🏀': 'Basketball',
  '⚽': 'Soccer'
};

export default Icon;
